### PR TITLE
Added COVID-19 Medical Face Mask Detection

### LINKED ISSUE #32: Face mask detection system
Hello @Aryan-Chharia 

I propose to develop a real-time face mask detection system using machine learning techniques. This project will involve building a detection model that can accurately identify whether individuals are wearing face masks by analyzing live video feed or images. The system will utilize deep learning algorithms, particularly convolutional neural networks (CNNs), to process facial features and detect the presence of masks. By leveraging popular libraries such as OpenCV, TensorFlow, and Keras, we can ensure the model is both efficient and scalable. This detection system can be beneficial in public safety applications, promoting adherence to health guidelines in various environments.

Please assign me this work and add labels gssoc and hacktoberfest

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
## Related Issue
None

NOTE: Kindly write in the following format -

Closes #32 

## Description
- First from images and annotations of people wearing mask , labelled the people wearing mask, not wearing masks and wearing masks improperly
- Analyzed dataset
- Data Augmentation
- Training model
- Created test.py to load created model , process given image and detect mask in image

-Additions :
    - Model Training Notebook
    - Loading and Testing Notebook
    - Dataset ( Images + Annotations )
    - Trained Model
    - README.md

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/f63f6af4-a68b-4b7d-a90d-1034cfdec0af

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by DarshAgrawal14** [comment]
@Aryan-Chharia i have submitted the PR, if any changes needed let me know , else i would appreciate it if you could merge the PR

**Comment by DarshAgrawal14** [comment]
@Aryan-Chharia  ,It's been four days since I submitted the PR. If there are no further changes needed, I would appreciate it if you could merge the PR.

**Comment by Aryan-Chharia** [comment]
@DarshAgrawal14, please add a results folder to show the outcomes of this project. It can include videos or photos. There are a lot of files (1710), which makes it hard to manage and download. Since most of the files are related to data, can you link to the data from the site you’re using instead of downloading it all? Also, please run the program again to check if the model works without needing to download the data.

**Comment by DarshAgrawal14** [comment]
okay , i will remove the files , model doesnt need them to work. just if user wants to train one it is required. here is a video showing working of model .

https://github.com/user-attachments/assets/7b83f1ec-cf58-4df4-955a-2cc9c3a500f5

, i have added this in PR as well as you said.

**Comment by DarshAgrawal14** [comment]
if anything else please let me know.

**Pull request merged**
