### PR TITLE
Added Image Captioning Project

### LINKED ISSUE #162: Add Image Captioning Project
This project implements an image captioning system that generates descriptive captions for images using deep learning techniques in computer vision and natural language processing. The model leverages a pre-trained InceptionV3 architecture for image feature extraction and an LSTM network for generating captions based on the extracted features. The dataset includes images and their corresponding captions, allowing the model to learn the relationships between visual content and textual descriptions. The project also includes utilities for image preprocessing and model training. This project serves as a foundation for exploring advanced techniques in image captioning, such as attention mechanisms and transfer learning.

### PR DESCRIPTION
**Pull request by adwityac**
## Related Issue
#162 

NOTE: Kindly write in the following format -

Closes #162 

## Description
This project has been enhanced with several improvements to the image captioning system. Recent updates focus on optimizing both the visual and textual components of the model. The image processing pipeline now supports multiple pre-trained CNN architectures, allowing for more flexible feature extraction. On the language side, the text preprocessing has been refined, and the sequence generation model has been tuned for better performance. These changes aim to produce more accurate and diverse image captions, improving the overall quality of the system's output.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [✅] Other (specify): Added a new project.

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
Add a results section as well

**Comment by adwityac** [comment]
Alright, what should I add specifically in the result section?

**Comment by Aryan-Chharia** [comment]
Add the input - what input the image is and the output of it - what is the captions on it

**Comment by adwityac** [comment]
Added Results in the py notebook file

**Comment by Aryan-Chharia** [comment]
@adwityac Can you add the results in a seperate folder under the project. It will be easier to see

**Comment by adwityac** [comment]
@Aryan-Chharia Added the results in separate folder and updated the readme in proper format. :)

**Pull request merged**
