### PR TITLE
Optimized YOLO object detection in main.py

### PR DESCRIPTION
**Pull request by BigBang001**
**Description**: Optimized YOLO object detection in main.py. This addresses issue #10, which outlines the need for performance enhancements and code refactoring.

**Changes Made**:
- Refactored the code to improve readability and performance, specifically focusing on the image preprocessing and object detection pipeline.
- Reduced the hardcoded paths for loading model weights, config files, and class names to make the code more flexible and user-friendly.
- Implemented error handling for image loading to prevent crashes if the image path is incorrect or the file is missing.
- Optimized the Non-Maximum Suppression (NMS) parameters to potentially enhance detection accuracy.

**Performance Improvements**:
- **Dynamic Paths**: By removing hardcoded paths and using relative paths or configurable settings, the script can now be run on different machines without modification, improving usability.
- **Error Handling**: Added checks for loading images to ensure the program fails gracefully, providing feedback to the user instead of crashing.
- **NMS Optimization**: Adjusted the confidence threshold and NMS parameters to potentially increase the accuracy of detected objects, reducing false positives and improving the overall reliability of detections.

**Specific Areas of Optimization**:
- The image resizing process was streamlined by ensuring consistent input dimensions to the YOLO model.
- The use of NumPy's efficient array operations was maximized during the processing of detection outputs.
- The random color generation for bounding boxes was optimized to ensure a consistent and visually appealing output.

**Why These Changes Were Made**:
These optimizations were made to enhance the user experience and performance of the object detection feature. By improving the structure and handling of the code, we aim to make it more maintainable and accessible to users, while also enhancing the accuracy of object detections. These changes ensure that the project adheres to best practices in coding standards, making it easier for future contributors to understand and build upon the work.

### CODE REVIEW

**Comment by BigBang001** [comment]
#10

**Comment by BigBang001** [comment]
Description Updated

**Comment by Aryan-Chharia** [comment]
Hello @BigBang001 I cannot merge this PR. I havent assigned the issue to you. Kindly first raise an issue. Then when its assigned to you then make a PR. I would suggest you close this PR. Then issue a fresh issue. This issue can be the improvement you suggest. Once issue is assigned then make a fresh PR. It would help in proper management of this repo. Thanks

**Comment by BigBang001** [comment]
Hello! I understand your request regarding the management of this repository. I have closed this pull request and will create a new issue outlining the proposed improvements for optimizing YOLO object detection in main.py. Once assigned to the issue, I will submit a fresh pull request for the changes. Thank you for your guidance!

**Pull request closed without merging**
