### PR TITLE
Empty Parking Spot Detection using CNN and OpenCV

### PR DESCRIPTION
**Pull request by Deekshu966**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

NOTE: Kindly write in the following format -

Closes #issue-number

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
cite the issue number

**Comment by Deekshu966** [comment]
#299

**Comment by Deekshu966** [comment]
Where should I link issue number

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Aryan-Chharia** [comment]
you have to make an issue first and then when assigned, then make a PR request. You cant make a PR before you are assigned the issue. Make an issue first and then open the PR again when it is assigned.

**Pull request closed without merging**
