### PR TITLE
ai-virtual-painter

### LINKED ISSUE #31: AI Virtual Painter Project
Hello @Aryan-Chharia ,

I would like to contribute a project called AI Virtual Painter to this repository. This project allows users to paint on a virtual canvas using hand gestures detected via a webcam. It's a great interactive tool that demonstrates the power of computer vision for real-time interaction and creativity.

Please assign me this issue so I can begin working on it.

### PR DESCRIPTION
**Pull request by Rohit131313**
## Related Issue
AI Virtual Painter Project

NOTE: Kindly write in the following format -

Closes #31 

## Description
This pull request introduces the development of the AI Virtual Painter, a dynamic tool that transforms a camera feed into an interactive canvas. Utilizing advanced computer vision techniques and hand-tracking algorithms, the system enables real-time drawing and writing, allowing users to create digital art that materializes directly on the screen. The integration of these technologies ensures a seamless, responsive user experience, enhancing creativity and interactivity.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
https://github.com/user-attachments/assets/c7ee81bd-33e5-40c1-b7ad-f96df0464f2e

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Please refer to the README.md file for setup instructions, usage guidelines, and environment configuration necessary to run the AI Virtual Painter.

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
kindly include the video in the PR as well

**Comment by Rohit131313** [comment]
Sir, I have already added the screen recording video functionality to the project.

**Comment by Aryan-Chharia** [comment]
hello @Rohit131313 kindly include the video (which you have included in this PR description, under screenshot) in the PR as well, as a result of this project.

**Comment by Rohit131313** [comment]
Sir, I have done the changes in PR as you asked to do please review once

**Comment by Aryan-Chharia** [comment]
Hello I cannot see the changes in the PR. Can you verify the PR once more ? I think you need to update the PR for me to see the changes.

**Pull request merged**
