### PR TITLE
Cloth Classifier

### PR DESCRIPTION
**Pull request by bhatiatanish225**
## Description
Add Clothing Classification Model using TensorFlow and MNIST Dataset
## Issue Number: #50 

1. Implemented a deep learning model using TensorFlow to classify images of clothing from the Fashion MNIST dataset.
2. The model is trained on 60,000 training images and evaluated on 10,000 test images, each belonging to one of 10 different fashion categories (e.g., T-shirt/top, trouser, dress, etc.).
3. Included data preprocessing steps such as normalization to scale pixel values and reshaping to fit the model's input layer.
4. Added functionality for visualizing the classification results and analyzing misclassified examples.

## Dataset Selection (Fashion MNIST):

- Importance: The Fashion MNIST dataset is a well-known benchmark dataset, making it easier to compare the model's performance with other implementations. It includes more complex images compared to the original MNIST digits dataset, making it a better testbed for image classification models that need to generalize across different types of objects.
- Impact: Helps to demonstrate proficiency in handling real-world classification problems involving complex patterns and shapes.

##  Model Implementation using TensorFlow:

- Importance: TensorFlow is one of the most widely used deep learning libraries, and implementing a model using it showcases an understanding of machine learning frameworks and their functionalities.
- Impact: Illustrates your ability to design, build, and train models using an industry-standard tool

## Model Performance and Accuracy:

- Importance: Evaluating the model's performance on the test set indicates how well it generalizes to new data. Reporting accuracy is crucial to assess whether the model meets the project's goals.
- Impact: Allows others to objectively evaluate the model's performance and suggest areas for improvement or alternative approaches.

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
@bhatiatanish225 Thanks you so much. This feels great! Can I ask you to include a readme file documenting what this project is all about ?

**Comment by bhatiatanish225** [comment]
@Aryan-Chharia  Sure sir , i will add it.

**Comment by Aryan-Chharia** [comment]
?

**Comment by bhatiatanish225** [comment]
Sir I will add it by tomorrow,
Sorry for the delay..

**Comment by Aryan-Chharia** [comment]
?

**Pull request merged**
