### PR TITLE
Add New Project AI Anime Avatar Generator Model #329

### LINKED ISSUE #329: Add New Project AI Anime Avatar Generator Model
#  AI Anime Avatar Generator using OpenCV and Matplotlib 

This repository contains a Python script to transform any given image into a smooth, anime-like avatar with soft edges, vibrant colors, and smooth shading transitions. The effect is inspired by traditional anime art styles. The project uses OpenCV and Matplotlib for image processing and display.
.
## 🛠️ Features
- Load an image from a file and display it in RGB format.
- Apply a smoother, more anime-like effect with soft edges and vibrant colors.
- Use Gaussian blurring, adaptive thresholding, and bilateral filtering to create the effect.
- Boost saturation and brightness to mimic anime-style vibrancy.
- Display the original image and the cartoonized image side by side.

## Python: 
The primary programming language for this project, known for its simplicity and a wide range of image processing libraries.
## OpenCV: 
A powerful open-source computer vision library that provides easy-to-use tools for image transformations and filters.
## NumPy: 
A fundamental library for scientific computing in Python, used for handling image arrays and numerical operations.
Matplotlib: A popular Python library for visualizing data. Here, it is used to display the images before and after processing.

### PR DESCRIPTION
**Pull request by Niraj1608**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

NOTE: Kindly write in the following format -

Closes #329 

## Description
**AI Anime Avatar Generator using OpenCV and Matplotlib**
Load an image from a file and display it in RGB format.
Apply a smoother, more anime-like effect with soft edges and vibrant colors.
Use Gaussian blurring, adaptive thresholding, and bilateral filtering to create the effect.
Boost saturation and brightness to mimic anime-style vibrancy.
Display the original image and the cartoonized image side by side.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
input
output

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Niraj1608** [comment]
@Aryan-Chharia kindly review my pr :)

**Comment by Niraj1608** [comment]
@Aryan-Chharia hey forgot to add a label on pr

**Comment by Aryan-Chharia** [comment]
my bad

**Comment by Niraj1608** [comment]
@Aryan-Chharia no problem

**Pull request merged**
