### PR TITLE
Added AI-Powered Super-Resolution and Image Restoration for Historical Photos model

### LINKED ISSUE #328: 🧑‍💻: AI-Powered Super-Resolution and Image Restoration for Historical Photos
### Title

AI-Powered Super-Resolution and Image Restoration for Historical Photos

### Enhancement Aim

This project aims to create an AI-Powered Image Restoration Tool that transforms low-quality historical photos by upscaling, denoising, and adding realistic color. Using deep learning, it revives old images with stunning clarity and detail, preserving memories in a vibrant, lifelike form. Perfect for heritage conservation and digital archiving!

### Changes

I want to add the model

### Screenshots 📷

_No response_

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Ankan

### Participant Role

GSSOC-24 EXTD

### PR DESCRIPTION
**Pull request by Peart-Guy**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”] None

NOTE: Kindly write in the following format -

Closes #328 

## Description

This project aims to create an AI-Powered Image Restoration Tool that transforms low-quality historical photos by upscaling, denoising, and adding realistic color. Using deep learning, it revives old images with stunning clarity and detail, preserving memories in a vibrant, lifelike form. Perfect for heritage conservation and digital archiving!

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Peart-Guy** [comment]
@Aryan-Chharia 
I have done the work. Kindly check it out and please give Level 3. It will be an honor

**Comment by Peart-Guy** [comment]
@Aryan-Chharia
I have done the work. Kindly check it out and please give Level 3. It will be an honor

**Comment by Aryan-Chharia** [comment]
add results as well. Also explain what the methodology you have used. Also remove your linkedin and github credentials. They are not required

**Comment by Peart-Guy** [comment]
@Aryan-Chharia  I have made the changes Kindly check it out

**Comment by Peart-Guy** [comment]
@Aryan-Chharia  Please give Level 3. it will be an honor

**Comment by Aryan-Chharia** [comment]
it won't be

**Comment by Peart-Guy** [comment]
> it won't be

At least level 2. as it is ML model

**Comment by Aryan-Chharia** [comment]
no

**Pull request merged**
