### PR TITLE
completed issue #1 (brightness control using opencv)

### PR DESCRIPTION
**Pull request by akashlogics**
**I have completed the issue I had been assigned**
In the upcoming days I will be raising more features and project ideas related to OpenCV 
**Thank you**

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
hello, i will review it at the earliest thanks

**Comment by Aryan-Chharia** [comment]
@akashlogics your PR has an issue. It is showing you have made 0 changes. And I cant see the changes you made. I think you have used some unsupported file or something. Kindly review your PR once more.

image

**Comment by akashlogics** [comment]
i used jupyter notebook to run my code

**Comment by Aryan-Chharia** [comment]
Hello, i cannot merge the PR unless it is correct. Make changes in the PR once again. Try different editor if the issue persist, please.

**Pull request closed without merging**
