### PR TITLE
Added Terrain classification

### LINKED ISSUE #158: Terrain Classification Using Transfer learning
hey @Aryan-Chharia 
I am Darsh Agrawal , a fellow contributor and I would like to contribute by using Transfer learning and create a model to help various agencies label captured terrain images like mountains, coast , desserts etc . By using transfer learning we can use pre trained models like RESNET or Efficientnet and hyperparameter tune them for terrain classification for better accuracy when compared to traditional CNN models.

Keys features :
- Data Augmentation to handle rotated images
- Handle images with filters
- Transfer Learning for better classification accuracy
-  Low Inferencing time , handles large datasets faster
- Low RAM usage and GPU compatible for parallel processing and even faster inference

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
## Related Issue
None

NOTE: Kindly write in the following format -

Closes #158 

## Description
created by using Transfer learning and create a model to help various agencies label captured terrain images like mountains, coast , desserts etc . By using transfer learning we can use pre trained models like RESNET or Efficientnet and hyperparameter tune them for terrain classification for better accuracy when compared to traditional CNN models.

Features:
- Used transfer learning for higher accuracy.
- Faster inference
- GPU compatible therefore label large datasets faster
- For more info refer [README](https://github.com/DarshAgrawal14/Computer-Vision-Projects/tree/main/Terrain_Classification#readme)

Added Files :
- Model Training notebook
- Loading and testing model notebook
- Inference and model stats calculator
- Readme.md
- Improvement.md

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/8094e33a-0bcd-45dd-bafb-1b001a88ce00

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
Add the video in a results section in the PR as well

**Comment by DarshAgrawal14** [comment]
> Add the video in a results section in the PR as well

@Aryan-Chharia  , just to clarify I have to create a section other than the on designated for screenshots and videos?

**Comment by Aryan-Chharia** [comment]
> @Aryan-Chharia , just to clarify I have to create a section other than the one designated for screenshots and videos?

You don’t need to update the PR description, as it’s meant for the moderator to understand the project you've submitted. Once the project is merged into the repository, the PR description won't be part of the final project. The video (currently in the description) should be included in the PR along with the code. For better readability, it’s recommended to place the video under the results section in the README file.

**Comment by DarshAgrawal14** [comment]
got it !

**Comment by DarshAgrawal14** [comment]
@Aryan-Chharia , Done ! have updated the readme to include video in result section. If anything else , let me know.

**Pull request merged**
