### PR TITLE
ECG Report Classification Using Computer Vision

### LINKED ISSUE #114: ECG Report Classification Using Computer Vision
Hi @Aryan-Chharia, 

I intend to contribute a CV based model which evaluates ECG reports.

**Objective:** Develop a computer vision model to accurately classify ECG reports into normal, history of MI, abnormal heartbeat, and myocardial infection.

**Overview:**
Deep learning can automate ECG image classification, improving diagnostic accuracy and efficiency. By preprocessing ECG images, training a suitable deep learning model (e.g., CNN, RNN), and evaluating its performance using appropriate metrics, we can develop models that can assist healthcare professionals in diagnosing heart conditions. However, addressing challenges like data quality, class imbalance, and interpretability is crucial for ensuring the reliability and clinical applicability of these models.

### PR DESCRIPTION
**Pull request by murtaza-sadri-19**
#### **ECG Report Classification Using Computer Vision**
Closes #114 

## Description
Implemented a new feature that allows users to filter ECG reports based on specific criteria, such as heart rate, QRS complex morphology, and ST-segment analysis. This will help users quickly identify ECG reports that match their specific needs.
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by murtaza-sadri-19** [comment]
Hi @Aryan-Chharia,
I am not getting this but when I open PR under #114, a new PR is generated under #121. So, I request you to review the changes and also assign labels to the PR.

**Comment by Aryan-Chharia** [comment]
> Hi @Aryan-Chharia, I am not getting this but when I open PR under #114, a new PR is generated under #121. So, I request you to review the changes and also assign labels to the PR.


This is fine

**Comment by Aryan-Chharia** [comment]
@murtaza-sadri-19 Thanks for the PR. As you can see, the files changed are huge (930 to be exact). I am not even able to review it fully. I was thinking since most of the files are dataset, can you just import the dataset in the file, and host the dataset somewhere in the public and provide the link in a readme file ? Of course if the dataset is already in the public domain you can just reference the link in a readme file and remove the datasets from the PR. Can you explore this ?

Additionally like in all other PR, please include a readme file explaining what your project is about and the methodology you followed. Thank you.

**Comment by murtaza-sadri-19** [comment]
Hi @Aryan-Chharia, I have made the changes. Please review the PR

**Pull request merged**
