### PR TITLE
AI Calculator Using Computer Vision and GenAI

### LINKED ISSUE #61: AI Calculator Using Computer Vision and GenAI
This project creates a gesture-controlled virtual calculator, allowing users to perform basic arithmetic and trigonometric calculations using hand gestures instead of a traditional keyboard or mouse. Users can wave their hands in front of a camera to recognize specific gestures linked to mathematical operations. For trigonometric functions, users can draw shapes (like triangles, squares, circles) to perform operations such as sine, cosine, and tangent calculations based on the shapes they create. An AI component interprets the shapes and executes the corresponding trigonometric operations.

### PR DESCRIPTION
**Pull request by ananyag309**
Closes #61 AI Calculator Using Computer Vision and GenAI

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
Kindly include a video of the project, showcasing the results, as a results in the file.

**Comment by Aryan-Chharia** [comment]
?

**Comment by ananyag309** [comment]
@Aryan-Chharia will be uploading it till Monday, sorry for delay stuck in college mid sem exam

**Comment by Satyabrat2005** [comment]
@Aryan-Chharia should i perform this project with a video ? 
i will surely send you video by tonight or by tomorrow morning ?

**Comment by Aryan-Chharia** [comment]
?

**Pull request merged**
