### PR TITLE
Eye-Controlled Mouse using Eye Tracking

### LINKED ISSUE #225: Enable Mouse Control through Eye Tracking
#### Description
Implement a feature that allows users to control the mouse cursor using their eye movements. This functionality aims to enhance accessibility for users with mobility impairments and provide an innovative way to interact with the application.

#### Objectives
- Develop an eye-tracking system that accurately detects and interprets users' eye movements.
- Translate eye movements into mouse cursor movements, allowing users to navigate the interface seamlessly.
- Implement click functionality triggered by specific eye gestures (e.g., blinking, gaze hold).

### PR DESCRIPTION
**Pull request by IkkiOcean**
## Related Issue
- Closes #225 

## Description
This pull request implements mouse control and click functionality using eye tracking with **MediaPipe** and **PyAutoGUI**. This feature enables users to control the mouse cursor and trigger clicks based on their eye movements, offering hands-free interaction with the system. It benefits users with limited mobility and enhances accessibility by providing an alternative input method.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
WhatsApp Image 2024-10-20 at 19 28 41

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
This feature is designed to enhance accessibility for users with limited mobility, allowing them to interact with the system more effectively. The eye-tracking functionality is achieved by mapping facial landmarks to screen coordinates and detecting blinks for simulating mouse clicks.

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
add the results

**Comment by IkkiOcean** [comment]
@Aryan-Chharia 

like how? my picture? I actually dont wanna add my personal video to the repo. is that fine?

**Comment by Aryan-Chharia** [comment]
you can try to run the program on a video from internet.

**Comment by IkkiOcean** [comment]
@Aryan-Chharia please accept it without it as it uses opencv to detect eyes and making a video to show mouse movement and clicks by blinking will require me to create two videos (one of screen with mouse movement and other of me showing it image from internet With eyes and movement) and edit them also. please understand my pov

**Pull request merged**
