### PR TITLE
Real-time-carParking-detection..

### LINKED ISSUE #30: Real time parking space detection project using opencv
I would like to add a project in which we can check in an image or in a video how many parking slots are available in realtime with number of available spaces(count)
@Aryan-Chharia assign it to me.
please look into this @Vaibhav22p-qw @c0sm0void

### PR DESCRIPTION
**Pull request by Meetpidev**
## Related Issue
None

Closes #30 

## Description
Real-time-parking-space-detection using opencv..

## Type of PR
- Feature enhancement

## video:
https://github.com/user-attachments/assets/eb964e19-da1f-4b02-bba9-18e735a1a8c3

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
you just simply need to run ipynb file..

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Aryan-Chharia Please Review PR...

**Comment by Aryan-Chharia** [comment]
kindly add a readme file telling what your project is all about. Also add the results (this video should be fine)

**Comment by Meetpidev** [comment]
> kindly add a readme file telling what your project is all about. Also add the results (this video should be fine)

@Aryan-Chharia Its done..

**Comment by Meetpidev** [comment]
@Aryan-Chharia Review PR againg..

**Pull request merged**
