### PR TITLE
#220 Added AI 3D Object Reconstruction Python Script

### LINKED ISSUE #216: Add 3D Object Reconstruction
@Aryan-Chharia  I want to add 3D Object Reconstruction using OpenCV 

Here this project aimed at creating 3D models of objects by capturing two or more images from different viewpoints.
Tech stack will be used are :- Python , StereoBM(OpenCV) , numpy, point cloud library and using matplotlib 

i will use more tech stack for getting more precisely and accurate image

Please assign this project to me @Aryan-Chharia  !!

### LINKED ISSUE #220: Add 3D Object Reconstruction
@Aryan-Chharia i want to contribute in this project 

Main theme of this project :- 3D Object Reconstruction using Stereo Vision involves capturing two images of a scene from slightly different perspectives. By comparing these images, a disparity map is generated, which shows the difference in position between corresponding points in the two images. 

Using this disparity data, depth information is calculated, allowing the reconstruction of the 3D structure of the scene.

Here are some examples 

left_image
Here is Left image (of my room)

right_image
Here is Right image (of my room)

And here is the DISPARITY IMAGE
Screenshot 2024-10-17 104329

### PR DESCRIPTION
**Pull request by Satyabrat2005**
This commit adds the Python script implementing the AI 3D Construction solution as described in issue

## Related Issue
[#216 ]

Closes #216 

## Description
This pull request adds a Python script for the AI 3D Construction project. The script includes functionality to 3D object reconstruction using stereo vision, the black and white colors in a disparity map . It aims to solve the issue raised in #220 by implementing a robust AI solution.

White (or lighter areas):

Represents objects that are closer to the camera.

The brighter the area, the closer the object or surface in that part of the scene.

Black (or darker areas):

Represents objects that are farther away from the camera.

The darker the area, the farther the object or surface is.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos 
Screenshot 2024-10-17 213410

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
This AI 3D Construction script uses advanced algorithms to simulate and predict :- 

Depth Information: The disparity map provides information about the relative depth of objects in the scene. Brighter areas are close, while darker areas are far. 

3D Scene Understanding: You can interpret the structure of the scene from this map, as it shows how different objects are positioned in relation to the camera.

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
@Satyabrat2005 Add the correct issue number in the PR description. #220 is closed. You have another assigned issue. Check that

**Comment by Aryan-Chharia** [comment]
#216 is the issue. Dont close this issue on your own

**Comment by Satyabrat2005** [comment]
> #216 is the issue. Dont close this issue on your own

sure sir

**Comment by Aryan-Chharia** [comment]
@Satyabrat2005 add a readme file and a methodology file explaining what your project is all about and what is the method you used and explanation of that method

**Comment by Satyabrat2005** [comment]
> @Satyabrat2005 add a readme file and a methodology file explaining what your project is all about and what is the method you used and explanation of that method

sure sir

**Comment by Satyabrat2005** [comment]
> @Satyabrat2005 add a readme file and a methodology file explaining what your project is all about and what is the method you used and explanation of that method

sir do i need to write methodology file as I have explain everythin in README.md file

**Pull request merged**
