### PR TITLE
Added Image segmentations in real time

### LINKED ISSUE #243: Segment Anything in Real Time
Adding a project, where we would be able to segment anything in real time using Fastsam.

Reference: - https://github.com/CASIA-IVA-Lab/FastSAM?tab=readme-ov-file

### PR DESCRIPTION
**Pull request by jaidh01**
## Related Issue
#243 

NOTE: Kindly write in the following format -

Closes #243 

## Description
I have used FastSam for image segmentation as it takes comparatively much lesser time than any other model present.
Although it was for images only, but after doing some changes in its source file, now we are able to use it in real time as well.

The user can choose from 4 segmentation choices: - everything, box, text and point segementations.

## Type of PR

- [] Bug fix
- [x] Feature enhancement
- [] Documentation update
- [] Other (specify): _______________

## Screenshots / videos (if applicable)
I added the ss of images, but it will perform same in real time as well.

original image: -  
download

Updated Image: - 
download (1)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
add results and readme and methodology

**Comment by jaidh01** [comment]
@Aryan-Chharia, I have done all the changes.

**Comment by jaidh01** [comment]
Hi @Aryan-Chharia, 
I have a small request from you. As I have to do multiple changes in the `original FastSam repo`, to use it in real time, which was a bit difficult task, hence I request you to please change the `level label` from `level 1` to `level 3`.

**Comment by jaidh01** [comment]
@Aryan-Chharia thanks for merging the PR. 
I request you to please improving the `level` `label` from `level 1` to `level 3`. As, I have to do multiple changes in the source file to implement this in real time.

**Comment by Aryan-Chharia** [comment]
wait i am confirming

**Comment by Aryan-Chharia** [comment]
@jaidh01 project additions are level 1 only. I have given level 2 but I cannot give level 3. Thanks for understanding.

**Pull request merged**
