### PR TITLE
added face recognition project

### PR DESCRIPTION
**Pull request by anirudh-248**
## Related Issue
Face Recognition System #58

## Description
Added the face recognition system project

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): new project

## Screenshots/videos (if applicable)
N/A

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Additional context:
I have also added an attendance feature along with my face recognition project.
The face_rec.py file detects and recognizes faces from a given image, the smart_attendance.py file does the same but through video capture. Please review this PR @Aryan-Chharia

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
Kindly include a description of the project in the readme file. Also if possible please include a screenshot of the results as well

**Comment by anirudh-248** [comment]
added a description of the project and included screenshots, once the pull request has been merged, I can add a permanent link to the readme file

**Comment by Aryan-Chharia** [comment]
@anirudh-248 once the pull request has been merged you cannot add anything extra to it. Kindly add the links in the readme files as well. thank you

**Comment by anirudh-248** [comment]
@Aryan-Chharia I have added the permalinks for the images in the readme file, please let me know if anything else is needed.

**Pull request merged**
