### PR TITLE
Create README.md

### LINKED ISSUE #307: 🧑‍💻: object size detection
### Title

object size detection

### Enhancement Aim

object size detection model involves using computer vision techniques to estimate the physical dimensions of an object in an image.

### Changes

Adding features by incorporating a computer vision model.

### Screenshots 📷

N/A

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Sameer Desai

### Participant Role

GSSOC

### PR DESCRIPTION
**Pull request by Sameeratweb**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

NOTE: Kindly write in the following format -

Closes #307 

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Aryan-Chharia** [comment]
the images in readme not showing

**Comment by Sameeratweb** [comment]
Screenshot 2024-11-04 211635
Are you saying this? From my side, the images are displaying. Please let me know .

**Comment by Aryan-Chharia** [comment]
image

**Comment by Sameeratweb** [comment]
ive made some changes, please  check it whether it is getting displayed or not?

**Comment by Sameeratweb** [comment]
My points are not getting reflected in gssoc leaderboard , do you have any idea?

**Comment by Aryan-Chharia** [comment]
I believe it is showing. 
image
contact the program manager through the discord server if there is a problem.

**Pull request merged**
