### PR TITLE
Issue#144 object dedection by colour

### LINKED ISSUE #144: feat: dedecting object by colour HSV
# Tracking Using HSV 
In this Example i tried to track objects with blue colors .(Blue is life :sunglasses:).

I used Trackbars to manipulate the values for blue range ,the following results are expressed interms of lowerValue(71,112,112) up to (255,255,255) .
#### Required Modules :
  - Numpy   
    ```bash
      pip install numpy
    ```
  - Opencv   
    ```bash
      pip install opencv-python
    ```
#### Results : 
HSV_Results

### PR DESCRIPTION
**Pull request by akashlogics**
## Related Issue
finding the objects by there colour and I used to find blue colour objects 

NOTE: Kindly write in the following format -

Closes #144 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Screenshots/videos (if applicable)
HSV_Results

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by akashlogics** [comment]
@Aryan-Chharia  please label gssoc24-extd and hacktoberfest and level

**Comment by akashlogics** [comment]
@Aryan-Chharia can i know the mistakes done in my PR as is not merged

**Comment by Aryan-Chharia** [comment]
You have to make a PR once the issue and been assigned to you.

**Comment by akashlogics** [comment]
> You have to make a PR once the issue and been assigned to you.

issue no #1

**Comment by Aryan-Chharia** [comment]
@akashlogics kindly wait. I will check and see if there is an issue. Keep an eye for my message

**Comment by Aryan-Chharia** [comment]
@akashlogics You have been assigned just 1 issue. The first issue #1. No other issue has been assigned to you. You have to wait till you are assigned an issue, and then start working on it. Besides this PR isn't even related to the issue assigned. It's totally different. Also I checked your other PR's. I have suggested changes in that, however you have closed that PR (for some reasons) and didn't open another PR. I won't assign any other issue till the existing issues have been completed.

**Pull request closed without merging**
